name: patterns_repro
publish_to: none

version: 3.2.11+5138

environment:
  sdk: ^3.0.0

dependencies:
  patterns_core:
    path: ../../packages/patterns_core
  expandable: ^5.0.1

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^12.1.2
  meta: ^1.8.0
  provider: ^6.0.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
